apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["spot"]
    - key: "node.kubernetes.io/instance-type" 
      operator: In
      values: ["t3.micro","t3.small","t3.medium","t3.large","t3.xlarge","t3a.micro","t3a.small","t3a.medium","t3a.large","t3a.xlarge"]
  limits:
    resources:
      cpu: 1000
  ttlSecondsAfterEmpty: 30
  providerRef:
    name: default
---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: default
spec:
  subnetSelector:
    cluster-name: {{{ .global.Rafay.ClusterName }}}
  securityGroupSelector:
    cluster-name: {{{ .global.Rafay.ClusterName }}}
  tags:
    email: tim@rafay.co
    env: qa