apiVersion: opa.k8smgmt.io/v3
kind: OPAPolicy
metadata:
  name: opa-gs-policy
  project: defaultproject
spec:
  constraintList:
  - name: rafay-request-limit-ratio-constraint
    version: v1
  - name: rafay-gatekeeper-allowedrepos-constraint
    version: v1
  sharing:
    enabled: true
    projects:
    - name: defaultproject
  version: opa-gs-policy-version
