apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: kubevirt-blueprint
  project: defaultproject
spec:
  base:
    name: minimal
  customAddons:
  - name: kubevirt-operator-addon
    version: v1
  - dependsOn:
    - kubevirt-operator-addon
    name: kubevirt-cr-addon
    version: v1
  defaultAddons:
    enableIngress: false
    enableLogging: true
    enableMonitoring: true
    enableVM: false
    monitoring:
      helmExporter:
        discovery: {}
        enabled: true
      kubeStateMetrics:
        discovery: {}
        enabled: true
      metricsServer:
        enabled: false
      nodeExporter:
        discovery: {}
        enabled: true
      prometheusAdapter:
        enabled: false
      resources: {}
  drift:
    enabled: true
  sharing:
    enabled: false
  version: v1