apiVersion: v1
kind: Pod
metadata:
  name: tensorflow
spec:
  restartPolicy: OnFailure
  containers:
  - name: tensorflow
    image: "nvcr.io/nvidia/tensorflow:22.02-tf2-py3"
    command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 3600']
    command: ['sh', '-c', './nvidia-examples/cnn/resnet.py']
    resources:
      limits:
         nvidia.com/gpu: 1