kind: ManagedNamespace
apiVersion: config.rafay.dev/v2
metadata:
  name: triton
  labels:
  annotations:
spec:
  type: RafayWizard
  resourceQuota:
  placement:
    placementType: ClusterSpecific
    clusterLabels:
    - key: rafay.dev/clusterName
      value: eks-gpu-triton